version: "3"
services:
       canvas-ms-container:
           container_name: canvas-ms-container
           image: canvas-ms
           restart: always
           build:
            context: .
            dockerfile: Dockerfile
           ports:
             - "3001:3001"

